modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "myrtrees"
version = "${version}"
displayName = "Myrtrees"
authors = "Jake_E"
description = '''
Myrtrees
'''

[[dependencies.myrtrees]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.myrtrees]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.myrtrees]]
modId = "architectury"
mandatory = true
versionRange = "[5.6.21,)"
ordering = "AFTER"
side = "BOTH"